# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys
import random
from PyQt5.QtGui import *
import math
from pageshu import eliminate1, eliminate2


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 852)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.memory_record = []
        self.page_table = []
        self.work_set = []
        self.page_river = []
        self.current_position = 0
        self.current_memory = []
        self.current_memory_position = 0
        self.page_river_position = 0
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_1.setGeometry(QtCore.QRect(80, 90, 291, 581))
        self.tableWidget_1.setRowCount(32)
        self.tableWidget_1.setColumnCount(16)
        self.tableWidget_1.setObjectName("tableWidget_1")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(15, item)
        self.tableWidget_1.horizontalHeader().setVisible(False)
        self.tableWidget_1.horizontalHeader().setDefaultSectionSize(18)
        self.tableWidget_1.horizontalHeader().setMinimumSectionSize(18)
        self.tableWidget_1.verticalHeader().setVisible(False)
        self.tableWidget_1.verticalHeader().setDefaultSectionSize(18)
        self.tableWidget_1.verticalHeader().setHighlightSections(False)
        self.tableWidget_1.verticalHeader().setMinimumSectionSize(18)
        self.random_Distribution()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(560, 120, 281, 451))
        self.tableWidget_2.setRowCount(64)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(131)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(30)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 40, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(1020, 200, 131, 291))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(128)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(36)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(30)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1030, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(620, 610, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 610, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.judge)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 610, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 750, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(620, 750, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(620, 680, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(860, 680, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.distribution)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 680, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(990, 750, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.flow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1320, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row0"))
        item = self.tableWidget_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Row1"))
        item = self.tableWidget_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Row2"))
        item = self.tableWidget_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Row3"))
        item = self.tableWidget_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Row4"))
        item = self.tableWidget_1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Row5"))
        item = self.tableWidget_1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Row6"))
        item = self.tableWidget_1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Row7"))
        item = self.tableWidget_1.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Row8"))
        item = self.tableWidget_1.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Row9"))
        item = self.tableWidget_1.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Row10"))
        item = self.tableWidget_1.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Row11"))
        item = self.tableWidget_1.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Row12"))
        item = self.tableWidget_1.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Row13"))
        item = self.tableWidget_1.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Row14"))
        item = self.tableWidget_1.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "Row15"))
        item = self.tableWidget_1.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "Row16"))
        item = self.tableWidget_1.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Row17"))
        item = self.tableWidget_1.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "Row18"))
        item = self.tableWidget_1.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "Row19"))
        item = self.tableWidget_1.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "Row20"))
        item = self.tableWidget_1.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "Row21"))
        item = self.tableWidget_1.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "Row22"))
        item = self.tableWidget_1.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "Row23"))
        item = self.tableWidget_1.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "Row24"))
        item = self.tableWidget_1.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "Row25"))
        item = self.tableWidget_1.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "Row26"))
        item = self.tableWidget_1.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "Row27"))
        item = self.tableWidget_1.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "Row28"))
        item = self.tableWidget_1.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "Row29"))
        item = self.tableWidget_1.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "Row30"))
        item = self.tableWidget_1.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "Row31"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Column0"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Column1"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Column2"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Column3"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Column4"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Column5"))
        item = self.tableWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Column6"))
        item = self.tableWidget_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Column7"))
        item = self.tableWidget_1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Column8"))
        item = self.tableWidget_1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Column9"))
        item = self.tableWidget_1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Column10"))
        item = self.tableWidget_1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Column11"))
        item = self.tableWidget_1.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Column12"))
        item = self.tableWidget_1.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Column13"))
        item = self.tableWidget_1.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Column14"))
        item = self.tableWidget_1.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Column15"))
        self.label.setText(_translate("MainWindow", "内存分配情况"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "Row2"))
        item = self.tableWidget_2.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "Row3"))
        item = self.tableWidget_2.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "Row4"))
        item = self.tableWidget_2.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "Row5"))
        item = self.tableWidget_2.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "Row6"))
        item = self.tableWidget_2.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "Row7"))
        item = self.tableWidget_2.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "Row8"))
        item = self.tableWidget_2.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(40)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(41)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(42)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(43)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(44)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(45)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(46)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(47)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(48)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(49)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(50)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(51)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(52)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(53)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(54)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(55)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(56)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(57)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(58)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(59)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(60)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(61)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(62)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(63)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "页号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "页框号"))
        self.label_2.setText(_translate("MainWindow", "页表"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_3.setText(_translate("MainWindow", "驻留集"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.label_4.setText(_translate("MainWindow", "请求内存:"))
        self.label_5.setText(_translate("MainWindow", "物理地址:"))
        self.pushButton_2.setText(_translate("MainWindow", "确定"))
        self.label_6.setText(_translate("MainWindow", "逻辑地址:"))
        self.pushButton_3.setText(_translate("MainWindow", "按照预设页流继续运行"))

    def random_Distribution(self):  # 随机分配内存
        for i in range(171):
            t = random.randint(0, 511)
            if t not in self.memory_record:
                self.memory_record.append(t)
            else:
                continue
            i = int(t / 16)
            j = t % 16
            temp_item = QTableWidgetItem(' ')
            temp_item.setBackground(QColor(255, 0, 0))
            self.tableWidget_1.setItem(i, j, temp_item)

    def judge(self):  # 判断请求是否合理
        require_memory = int(self.lineEdit.text())
        if require_memory > 128:
            QMessageBox.about(self, '分配失败', '请求内存超过最大可分配')
        else:  # 如果请求合理，则将已分好的页输出到页表中
            page_number = math.ceil(require_memory / 2)
            for i in range(page_number):
                self.page_table.append(' ')
                temp_item1 = QTableWidgetItem(str(i))
                temp_item2 = QTableWidgetItem(self.page_table[i])
                self.tableWidget_2.setItem(i, 0, temp_item1)
                self.tableWidget_2.setItem(i, 1, temp_item2)
            for i in range(int(page_number * 3)):  # 随机产生页流
                flag = random.randint(0, len(self.page_table) - 1)
                self.page_river.append(flag)
            if page_number >= 8:
                current_memory_length = 8
            else:
                current_memory_length = page_number
            while len(self.current_memory) < current_memory_length:
                t = random.randint(0, 511)
                if t not in self.memory_record:
                    if t not in self.current_memory:
                        self.current_memory.append(t)
                        i = int(t / 16)
                        j = t % 16
                        temp_item = QTableWidgetItem(' ')
                        temp_item.setBackground(QColor(118, 255, 0))
                        self.tableWidget_1.setItem(i, j, temp_item)

    def distribution(self):  # 逻辑地址查询物理地址
        inquire_position = int(self.lineEdit_3.text())
        if inquire_position > len(self.page_table) * 2048:  # 查询超出最大可分配
            QMessageBox.about(self, '查询失败', '查询地址超出范围')
        else:  # 查询未超出最大可分配
            offset = inquire_position % 2048  # 计算偏移量
            page_number = int(inquire_position / 2048)  # 计算所在页
            f = 0  # 判断标志，如果查询页在驻留集中，则置为1，不在则不改变
            for i in range(len(self.work_set)):  # 循环查询页是否在驻留集中
                if self.work_set[i][0] == page_number:  # 判断查询地址对应页是否在驻留集中
                    if self.work_set[i][1] == 1:
                        pass
                    else:
                        self.work_set[i][1] = 1
                        self.current_position = (i + 1) % 8
                    physical_address = self.page_table[page_number] * 2048 + offset  # 计算物理地址
                    self.lineEdit_2.setText(str(physical_address))  # 输出物理地址
                    self.tableWidget_3.clearContents()
                    for j in range(len(self.work_set)):
                        newitem = QTableWidgetItem(str(self.work_set[j][0]))
                        self.tableWidget_3.setItem(j, 0, newitem)
                    newitem = QTableWidgetItem(str(self.work_set[i][0]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_3.setItem(i, 0, newitem)
                    QMessageBox.about(self, '未发生缺页', '查询页在当前驻留集中！')
                    f = 1  # 标志位置为1，退出循环
                    break
            if f == 0:  # 查询地址不在驻留集中
                if len(self.work_set) < 8:  # 驻留集中的项小于驻留集大小
                    temp_work = [page_number, 1]  # 设置驻留集子项，使用位置位1
                    self.work_set.append(temp_work)  # 驻留集子项加入驻留集尾
                    self.page_table[page_number] = self.current_memory[self.current_memory_position]
                    self.current_memory_position += 1
                    o = self.current_position
                    self.current_position = (self.current_position + 1) % 8  # 指针指向当前被置换驻留集的下一个位置
                    QMessageBox.about(self, '发生缺页', '驻留集未满，没有页被淘汰！')  # 提示发生缺页，但驻留集未满
                    physical_address = self.page_table[page_number] * 2048 + offset  # 利用新加入的页计算物理地址
                    self.lineEdit_2.setText(str(physical_address))  # 输出物理地址
                    self.tableWidget_3.clearContents()
                    for i in range(len(self.work_set)):
                        newitem = QTableWidgetItem(str(self.work_set[i][0]))
                        self.tableWidget_3.setItem(i, 0, newitem)
                    self.tableWidget_2.clearContents()
                    for i in range(len(self.page_table)):
                        newitem = QTableWidgetItem(str(i))
                        self.tableWidget_2.setItem(i, 0, newitem)
                        newitem = QTableWidgetItem(str(self.page_table[i]))
                        self.tableWidget_2.setItem(i, 1, newitem)
                    newitem = QTableWidgetItem(str(self.work_set[o][0]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_3.setItem(o, 0, newitem)
                    newitem = QTableWidgetItem(str(self.work_set[o][0]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_2.setItem(self.work_set[o][0], 0, newitem)
                    newitem = QTableWidgetItem(str(self.page_table[self.work_set[o][0]]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_2.setItem(self.work_set[o][0], 1, newitem)
                else:  # 驻留集已满，利用Clock策略进行页面淘汰
                    temp_sdu = []
                    for i in self.work_set:
                        temp_sdu.append(i[0])
                    print(temp_sdu)
                    self.work_set, self.page_table, self.current_position, eliminate_pagenumber = eliminate1(
                        self.work_set, self.page_table, page_number,
                        self.current_position)  # 调用已写好的在物理地址查询时发生缺页，缺页中断处理的方法
                    QMessageBox.about(self, '发生缺页', str(eliminate_pagenumber) + '号页被淘汰！')  # 提示，发生缺页并有页淘汰
                    self.tableWidget_3.clearContents()
                    for i in range(len(self.work_set)):
                        newitem = QTableWidgetItem(str(self.work_set[i][0]))
                        self.tableWidget_3.setItem(i, 0, newitem)
                    self.tableWidget_2.clearContents()
                    for i in range(len(self.page_table)):
                        newitem = QTableWidgetItem(str(i))
                        self.tableWidget_2.setItem(i, 0, newitem)
                        newitem = QTableWidgetItem(str(self.page_table[i]))
                        self.tableWidget_2.setItem(i, 1, newitem)
                    for i in range(len(temp_sdu)):
                        if temp_sdu[i] != self.work_set[i][0]:
                            newitem = QTableWidgetItem(str(self.work_set[i][0]))
                            newitem.setBackground(QColor('lightgreen'))
                            self.tableWidget_3.setItem(i, 0, newitem)
                            newitem = QTableWidgetItem(str(self.work_set[i][0]))
                            newitem.setBackground(QColor('lightgreen'))
                            self.tableWidget_2.setItem(self.work_set[i][0], 0, newitem)
                            newitem = QTableWidgetItem(str(self.page_table[self.work_set[i][0]]))
                            newitem.setBackground(QColor('lightgreen'))
                            self.tableWidget_2.setItem(self.work_set[i][0], 1, newitem)
                            break
                physical_address = self.page_table[page_number] * 2048 + offset  # 根据装入页所分配的页框号，计算物理地址
                self.lineEdit_2.setText(str(physical_address))  # 输出物理地址

    def flow(self):  # 按照预设页流进行运转
        if self.page_river_position == len(self.page_river):
            QMessageBox.about(self, '运行完成', '进程已经执行完成！！')
            self.tableWidget_1.clearContents()
            for t in range(len(self.memory_record)):
                i = int(self.memory_record[t] / 16)
                j = self.memory_record[t] % 16
                temp_item = QTableWidgetItem(' ')
                temp_item.setBackground(QColor(255, 0, 0))
                self.tableWidget_1.setItem(i, j, temp_item)
            return
        f = 0  # 循环标志位，标志当前请求页是否在驻留集中，在则置为1，不在则为0
        for i in range(len(self.work_set)):
            if self.work_set[i][0] == self.page_river[self.page_river_position]:  # 页流表中当前页等于驻留集中某页
                f = 1  # 标志位置为1
                if self.work_set[i][1] == 1:  # 驻留集中此项使用位为1,只用将页流位置加1
                    self.page_river_position += 1
                else:
                    self.work_set[i][1] = 1  # 如果驻留集中此项使用位为0，则改为1
                    self.current_position = (i + 1) % 8  # 驻留集指针从当前加1
                    self.page_river_position += 1  # 页流表位置加1
                    self.tableWidget_3.clearContents()
                    for k in range(len(self.work_set)):
                        newitem = QTableWidgetItem(str(self.work_set[k][0]))
                    self.tableWidget_3.setItem(k, 0, newitem)
                    self.tableWidget_2.clearContents()
                    for j in range(len(self.page_table)):
                        newitem = QTableWidgetItem(str(j))
                        self.tableWidget_2.setItem(j, 0, newitem)
                        newitem = QTableWidgetItem(str(self.page_table[j]))
                        self.tableWidget_2.setItem(j, 1, newitem)
                    newitem = QTableWidgetItem(str(self.work_set[i][0]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_3.setItem(i, 0, newitem)
                    newitem = QTableWidgetItem(str(self.work_set[i][0]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_2.setItem(self.work_set[i][0], 0, newitem)
                    newitem = QTableWidgetItem(str(self.page_table[self.work_set[i][0]]))
                    newitem.setBackground(QColor('lightgreen'))
                    self.tableWidget_2.setItem(self.work_set[i][0], 1, newitem)
                    break

        if f == 0:  # 当前请求页不在驻留集中
            if len(self.work_set) < 8:  # 驻留集长度小于8
                temp_work = [self.page_river[self.page_river_position], 1]  # 设置驻留集子项
                self.work_set.append(temp_work)  # 将驻留集子项加入驻留集中
                self.page_table[self.page_river[self.page_river_position]] = self.current_memory[
                    self.current_memory_position]
                self.current_memory_position += 1
                self.page_river_position += 1  # 页流表位置加1
                o = self.current_position
                self.current_position += 1  # 驻留集当前指针位置加1
                self.tableWidget_3.clearContents()
                for i in range(len(self.work_set)):
                    newitem = QTableWidgetItem(str(self.work_set[i][0]))
                    self.tableWidget_3.setItem(i, 0, newitem)
                self.tableWidget_2.clearContents()
                for i in range(len(self.page_table)):
                    newitem = QTableWidgetItem(str(i))
                    self.tableWidget_2.setItem(i, 0, newitem)
                    newitem = QTableWidgetItem(str(self.page_table[i]))
                    self.tableWidget_2.setItem(i, 1, newitem)
                newitem = QTableWidgetItem(str(self.work_set[o][0]))
                newitem.setBackground(QColor('lightgreen'))
                self.tableWidget_3.setItem(o, 0, newitem)
                newitem = QTableWidgetItem(str(self.work_set[o][0]))
                newitem.setBackground(QColor('lightgreen'))
                self.tableWidget_2.setItem(self.work_set[o][0], 0, newitem)
                newitem = QTableWidgetItem(str(self.page_table[self.work_set[o][0]]))
                newitem.setBackground(QColor('lightgreen'))
                self.tableWidget_2.setItem(self.work_set[o][0], 1, newitem)
            else:  # 驻留集长度等于8，调用已写好页面淘汰方法
                self.work_set, self.page_table, self.current_position, self.page_river_position, eliminate_pagenumber = eliminate2(
                    self.work_set, self.page_table, self.page_river[self.page_river_position], self.page_river_position,
                    self.current_position)
                self.tableWidget_3.clearContents()
                for i in range(len(self.work_set)):
                    newitem = QTableWidgetItem(str(self.work_set[i][0]))
                    self.tableWidget_3.setItem(i, 0, newitem)
                self.tableWidget_2.clearContents()
                for i in range(len(self.page_table)):
                    newitem = QTableWidgetItem(str(i))
                    self.tableWidget_2.setItem(i, 0, newitem)
                    newitem = QTableWidgetItem(str(self.page_table[i]))
                    self.tableWidget_2.setItem(i, 1, newitem)
                for i in range(len(self.work_set)):
                    if self.work_set[i][0] == self.page_river[self.page_river_position - 1]:
                        newitem = QTableWidgetItem(str(self.work_set[i][0]))
                        newitem.setBackground(QColor('lightgreen'))
                        self.tableWidget_3.setItem(i, 0, newitem)
                        newitem = QTableWidgetItem(str(self.work_set[i][0]))
                        newitem.setBackground(QColor('lightgreen'))
                        self.tableWidget_2.setItem(self.work_set[i][0], 0, newitem)
                        newitem = QTableWidgetItem(str(self.page_table[self.work_set[i][0]]))
                        newitem.setBackground(QColor('lightgreen'))
                        self.tableWidget_2.setItem(self.work_set[i][0], 1, newitem)
                        break


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
